### PR TITLE
OwO for Python

### PR DESCRIPTION
**Pull request by DuckMasterAl**

### CODE REVIEW

**Comment by DuckMasterAl** [comment]
Also @IamTheRealSami please add [https://owo.owo](https://owo.owo) as the repositories website like the uwu one.

**Comment by IamTheRealSami** [comment]
@DuckMasterAl sure, I'll do it once I'm back home.

**Comment by DuckMasterAl** [comment]
Ok :p

**Comment by IamTheRealSami** [comment]
@DuckMasterAl pushed.

**Comment by DuckMasterAl** [comment]
Ok, Thanks!

**Pull request merged**
